services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    restart: "always"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  minio-api-service:
    build:
      context: ../cloudlock-file-system/
      dockerfile: Dockerfile
    image: minio-api-service:latest
    restart: "always"
    depends_on:
      - promtail
      - minio
    ports:
      - "3000:3000"

  redis-api-service:
    build:
      context: ../cloudlock-redis-service
      dockerfile: Dockerfile
    image: redis-api-service:latest
    restart: "always"
    ports:
      - "3080:3080"
    depends_on:
      - promtail
      - redis

  redis:
    image: redis/redis-stack:latest
    command: redis-server --requirepass ${REDIS_PASSWORD} --dir /data
    restart: "always"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
      - "8001:8001"
    volumes:
      - redis-data:/data

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/config.yaml
      - loki-data:/loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3050:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=loki
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/usr/share/grafana/public/dashboards/home.json
    depends_on:
      - loki
    restart: "always"

volumes:
  minio_data:
  loki-data:
  grafana-data:
  redis-data:
