services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  minio-redis-api-service:
    build:
      context: ../cloudlock-file-system/
      dockerfile: infra/Dockerfile
    image: minio-redis-api-service:latest
    ports:
      - "3000:3000"

volumes:
  minio_data:
